version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - backend-node-modules:/usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    command: ./docker/dev.command.sh
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres:12.2
    networks:
      - webnet
    environment:
      TZ: GMT
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqdata_etc/:/etc/rabbitmq/
      - rabbitmqdata_lib/:/var/lib/rabbitmq/
      - rabbitmqdata_log/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
    networks:
      - webnet

networks:
  webnet:
volumes:
  pgdata:
  backend-node-modules:
  rabbitmqdata_etc:
  rabbitmqdata_lib:
  rabbitmqdata_log:
